name    'netmanagers-tcpwrappers'
version '1.0.0'
author  'Javier Bértoli'
license 'Apache2'
project_page 'http://www.netmanagers.com'
source  'https://github.com/netmanagers/puppet-tcpwrappers'
summary 'Puppet module for tcpwrappers'
description 'This module installs and manages tcpwrappers. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'camptocamp/augeas', '>= 0.0.1'
dependency 'puppetlabs/stdlib', '>= 2.2.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
